### ISSUE TITLE
Include wait_for_update on the setDefaultConsent Call

### ISSUE THREAD

**Issue by semisight** [OrbeeInc/gtm-consent-template#1]
https://github.com/OrbeeInc/orbee-consent-template-gtm/blob/4460dadd0c49473bda7073381692fbf335e24e46/template.tpl#L202

When reviewing your template we've noticed that the setDefaultConsentState call does not include the [wait_for_update](https://developers.google.com/tag-platform/tag-manager/templates/api#setdefaultconsentstate) option. This is required for any asynchronous consent management script load to delay tag execution.

**Comment by genfilipow** [comment]
@semisight I have added the wait_for_update option to the setDefaultConsentState call.
